# Generated by Django 4.2.24 on 2025-09-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = []
